batch_size: 64
height: 50
learning_rate: 0.001
max_text_length: 5
model_path: Models/02_captcha_to_text\202212211205
train_epochs: 1000
train_workers: 20
vocab: 45bnc87py3d6efgx2wm
width: 200
