batch_size: 64
height: 32
learning_rate: 0.001
max_text_length: 16
model_path: Models/03_handwriting_recognition/202301111911
train_epochs: 1000
train_workers: 20
vocab: z9k5ijq.E0TPr,LcfDyumotYKO-QJ;d:Bn?b8lNWHI4s6'g7U!1A3)pweV#MRF"GZvax&h(S2C
width: 128
