batch_size: 1024
height: 32
learning_rate: 0.0001
max_text_length: 16
model_path: Models/1_image_to_word\202302241920
train_epochs: 100
train_workers: 20
vocab: ''';&Q#sK"yoASIzE103ucjvLDYrBpx964?VkaMO!bTfg)CtlJ(G:27nq,UZRwdh-NWFHP.em8i'
width: 128
